# This is a basic workflow to help you get started with Actions

name: 1. Create a new caption-this class repository

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repo_name:
        type: text
        required: true
        default: "caption-this"
      
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run create-initial-repo
        env:
          TEACHER_PAT: ${{secrets.TEACHER_PAT}}
        run: script/create-initial-repo ${{github.event.inputs.repo_name}}

      
